// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ey5_xrjbKNSYkqKc63JgmZ0GUELYbKA',
    appId: '1:293742687659:web:636eb66e748b12be2c0eee',
    messagingSenderId: '293742687659',
    projectId: 'laporanmobile',
    authDomain: 'laporanmobile.firebaseapp.com',
    storageBucket: 'laporanmobile.firebasestorage.app',
    measurementId: 'G-0M0FB2WQVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDjDkW4mHyn-_hWN7riVULOgYJDvVaMyc',
    appId: '1:293742687659:android:1c50b0689ac29dcd2c0eee',
    messagingSenderId: '293742687659',
    projectId: 'laporanmobile',
    storageBucket: 'laporanmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDihMZu7pTiV9i7DtGm935lxFtTyvLI814',
    appId: '1:293742687659:ios:94e49ef7462e81542c0eee',
    messagingSenderId: '293742687659',
    projectId: 'laporanmobile',
    storageBucket: 'laporanmobile.firebasestorage.app',
    iosBundleId: 'com.google.laporan4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDihMZu7pTiV9i7DtGm935lxFtTyvLI814',
    appId: '1:293742687659:ios:94e49ef7462e81542c0eee',
    messagingSenderId: '293742687659',
    projectId: 'laporanmobile',
    storageBucket: 'laporanmobile.firebasestorage.app',
    iosBundleId: 'com.google.laporan4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ey5_xrjbKNSYkqKc63JgmZ0GUELYbKA',
    appId: '1:293742687659:web:a7022cf5b8e70a132c0eee',
    messagingSenderId: '293742687659',
    projectId: 'laporanmobile',
    authDomain: 'laporanmobile.firebaseapp.com',
    storageBucket: 'laporanmobile.firebasestorage.app',
    measurementId: 'G-CTNYP39H7V',
  );
}
